version: '3.15'
services:
  app:
    build:
      context: .
    volumes:
      - .:/FEESTPLANNERFRONT
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start
